version: "3.4"
services:
  jupyterlab:
    build: .
    ports:
      - "8888:8888"
    environment:
      - "JUPYTERLAB_S3_ENDPOINT=http://minio:9000"
      - "JUPYTERLAB_S3_ACCESS_KEY_ID=ACCESS_KEY"
      - "JUPYTERLAB_S3_SECRET_ACCESS_KEY=SECRET_KEY"
    command:
      - jupyter
      - lab
      - --ip=0.0.0.0
      - --no-browser
      - --ServerApp.password=''
      - --ServerApp.token=''
      - --allow-root
    # volumes:
      # - /Users/jamesreeve/.aws/:/root/.aws/ # replace <home_folder> with the path to your .aws folder and comment out the environment section below to use your aws account's s3 buckets instead

  minio:
    image: minio/minio
    command: server /data
    volumes:
      - ./minio-data/:/data
    ports:
      - "9000:9000"
    environment:
      - "MINIO_ACCESS_KEY=ACCESS_KEY"
      - "MINIO_SECRET_KEY=SECRET_KEY"
