{% set data = load_npm()%}
package:
  name: {{ data.get('name').lower() }}
  version: {{ data.get('version').replace("-","_") }}

source:
  path: .

about:
  summary: {{data.get('description')}}
  home: {{data.get('url')}}
  license: {{data.get('license')}}

requirements:
  build:
    - jupyter_packaging

build:
  noarch: python
  script: ls dist/ | xargs -I@ pip install --no-deps dist/@
