{% set data = load_npm()%}
package:
  name: {{ data.get('name').lower() }}
  version: {{ data.get('version').replace("-","_") }}

source:
  path: ..

about:
  summary: {{data.get('description')}}
  home: {{data.get('url')}}
  license: {{data.get('license')}}

build:
  noarch: python
  script: ls /home/runner/work/jupyterlab-s3-browser/jupyterlab-s3-browser/dist/ | xargs pip install --no-deps
