{% set data = load_npm()%}
package:
  name: {{ data.get('name').lower() }}
  version: {{ data.get('version') }}

source:
  path: ..

about:
  summary: {{data.get('description')}}
  home: {{data.get('url')}}
  license: {{data.get('license')}}

build:
  noarch: python
  script: pip install dist/{{ data.get('name').lower() }}-{{ data.get('version') }}-py3-none-any.whl
