package:
  name: "jupyterlab-s3-browser"
  version: { { .version } }

source:
  path: ..

about:
  summary: "A JupyterLab extension for browsing S3-compatible object storage"

build:
  noarch: python
  script: poetry install
