name: Cypress Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-20.04
    name: test
    services:
      minio:
        image: minio/minio
        env:
          MINIO_ACCESS_KEY: ACCESS_KEY
          MINIO_SECRET_KEY: SECRET_KEY
        ports:
          - 9000:9000
    strategy:
      matrix:
        jupyterlab_version: ["2.*", "3.*"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel twine setuptools packaging jupyterlab==${{ matrix.jupyterlab_version }} jupyter_packaging~=0.7.9
          jlpm
      - run: jupyter lab --version
      - run: jlpm install:extension
      - run: jupyter labextension list
      - run: jupyter serverextension list

      - uses: cypress-io/github-action@v2
        with:
          start: jupyter lab --no-browser --ServerApp.password='' --ServerApp.token=''
          # start: docker-compose up
          browser: chrome
          headless: true
          wait-on: "http://localhost:8888/lab"
          wait-on-timeout: 120
